# Generated by Django 5.1.2 on 2025-10-17 19:59

import api_rest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_user_medicalimageupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalimageupload',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterField(
            model_name='medicalimageupload',
            name='file',
            field=models.FileField(upload_to=api_rest.models.upload_path),
        ),
        migrations.AlterField(
            model_name='medicalimageupload',
            name='file_type',
            field=models.CharField(choices=[('jpg', 'Mamografia (JPG)'), ('png', 'Ultrassom (PNG)'), ('jpeg', 'Imagem JPEG'), ('dcm', 'Imagem DICOM')], max_length=10),
        ),
    ]
